"""Backtest arms that isolate the two Stage-B generation methodologies.

The historical candidate pool contains ideas from both generators. These
selectors do not rank across methods; each admits only the ideas produced by its
named generator. Running both over the same RunContext keeps the comparison
paired while attributing the difference to Stage B.
"""

from __future__ import annotations

from ..strategy import RunContext, Verdict, register


def _pick(ctx: RunContext, method: str, name: str) -> Verdict:
    chosen = [
        str(candidate["id"])
        for candidate in ctx.candidates
        if str(candidate.get("method") or "") == method
    ]
    return Verdict(
        strategy=name,
        version="1.0",
        chosen=chosen,
        rejected={
            str(candidate["id"]): f"generated by {candidate.get('method')}"
            for candidate in ctx.candidates
            if str(candidate.get("method") or "") != method
        },
        meta={
            "generation_method": method,
            "n": len(chosen),
            "selection": "method isolation; no cross-method ranking",
        },
    )


@register(
    "idea_selector",
    "generated_ai_native",
    "1.0",
    label="Pure AI native 生成臂",
    role="control",
    params={},
)
def generated_ai_native(ctx: RunContext) -> Verdict:
    return _pick(ctx, "ai_native", "generated_ai_native")


@register(
    "idea_selector",
    "generated_carl_constraint",
    "1.0",
    label="Carl constraint 生成臂",
    role="primary",
    params={},
)
def generated_carl_constraint(ctx: RunContext) -> Verdict:
    return _pick(ctx, "carl_constraint", "generated_carl_constraint")
